spring.application.name=jibrax

jwt.auth.converter.resource-id=jibrax-api
jwt.auth.converter.principal-attribute=preferred_username

logging.level.org.springframework.security=TRACE
logging.level.org.keycloak=DEBUG

server.port=8090

# --- DATABASE CONFIG ---
spring.datasource.url=url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jibrax}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- KEYCLOAK ADMIN CLIENT CONFIG ---
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=jibrax

keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.client-id=admin-cli

keycloak.client-id=jibrax-api
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/jibrax
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/jibrax/protocol/openid-connect/certs