spring.application.name=jibrax

jwt.auth.converter.resource-id=jibrax-api
jwt.auth.converter.principal-attribute=preferred_username

logging.level.org.springframework.security=TRACE
logging.level.org.keycloak=DEBUG

server.port=${PORT:8090}

# --- DATABASE CONFIG ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jibrax}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --- KEYCLOAK ADMIN CLIENT CONFIG ---
keycloak.auth-server-url=${KEYCLOAK_URL:http://localhost:8080}
keycloak.realm=jibrax

keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.client-id=admin-cli

keycloak.client-id=jibrax-api
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

# --- SPRING SECURITY OAUTH2 ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/jibrax
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.auth-server-url}/realms/jibrax/protocol/openid-connect/certs